version: "3"

services:
  app:
    image: node:fermium
    ports:
      - "3000:3000"
    command: tail -f /dev/null
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
    working_dir: /workspace

volumes:
  node_modules:
